[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["serde", "v4"] }
chrono = { version  = "0.4", features = ["serde"] }
rand = "0.7"
ed25519-dalek = "1"
x25519-dalek = "1"
base64 = "0.13"